[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python backend/manage.py migrate && python backend/manage.py collectstatic --noinput && gunicorn scuffers_api.wsgi:application --chdir backend --bind 0.0.0.0:$PORT"

[env]
PYTHON_VERSION = "3.12"