[build]
builder = "NIXPACKS"

[phases.setup]
aptPkgs = ["build-essential", "default-libmysqlclient-dev", "pkg-config"]

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn scuffers_api.wsgi:application --bind 0.0.0.0:$PORT"